# Generated by Django 3.1.2 on 2020-11-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccumulationMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'accumulation_mode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgumentsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'arguments_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgumentsGroupHasProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'arguments_group_has_processor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgumentsGroupHasSpecificParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'arguments_group_has_specific_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'argument_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=45, unique=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionI18N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=155, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'collection_i18n',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComputingModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'computing_module',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComputingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('ip', models.CharField(max_length=256)),
                ('cmd', models.CharField(max_length=256)),
                ('user', models.CharField(blank=True, max_length=64, null=True)),
                ('passwd', models.CharField(blank=True, max_length=256, null=True)),
                ('temp_dir', models.CharField(blank=True, max_length=256, null=True)),
                ('is_default', models.IntegerField()),
                ('external_temp_dir', models.CharField(max_length=256)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'computing_system',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComputingSystemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cmd_type', models.CharField(max_length=60)),
                ('comment', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'computing_system_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conveyor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'conveyor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.FloatField()),
                ('offset', models.FloatField()),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'data_kind',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('is_visible', models.IntegerField()),
                ('time_start', models.CharField(max_length=10)),
                ('time_end', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dataset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'data_variable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_output', models.IntegerField()),
                ('to_input', models.IntegerField()),
            ],
            options={
                'db_table': 'edge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pattern', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'file_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geoportal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'geoportal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuiElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'gui_element',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuiElementI18N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=145, null=True, unique=True)),
            ],
            options={
                'db_table': 'gui_element_i18n',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LevelI18N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'level_i18n',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LevelsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'levels_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LevelsGroupHasLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'levels_group_has_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OptionsOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'options_override',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'option_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OptionValueI18N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'option_value_i18n',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationI18N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'organization_i18n',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterI18N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'parameter_i18n',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.IntegerField()),
                ('arguments_selected_by_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'processor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessorHasArguments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument_position', models.IntegerField()),
            ],
            options={
                'db_table': 'processor_has_arguments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessorHasOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'processor_has_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessorHasTimePeriodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'processor_has_time_period_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessorI18N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=145, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('reference', models.CharField(blank=True, max_length=245, null=True)),
            ],
            options={
                'db_table': 'processor_i18n',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'property_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('subpath1', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'resolution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RootDir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'root_dir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('subpath0', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'scenario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecificParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'specific_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimePeriodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'time_period_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimePeriodTypeI18N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'time_period_type_i18n',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=45, unique=True)),
                ('subpath2', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'time_step',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeStepI18N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'time_step_i18n',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitsI18N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'units_i18n',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'variable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'vertex',
                'managed': False,
            },
        ),
    ]
