# Generated by Django 3.1.2 on 2020-11-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectioni18n',
            options={'managed': True},
        ),
    ]
