# Generated by Django 3.1.2 on 2020-11-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadb', '0002_auto_20201106_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectioni18n',
            options={'managed': False},
        ),
    ]
