# Generated by Django 3.1.4 on 2021-03-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadb', '0003_auto_20201106_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConveyorHasVertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertex_position_top', models.IntegerField()),
            ],
            options={
                'db_table': 'conveyor_has_vertex',
                'managed': False,
            },
        ),
    ]
