# Generated by Django 3.1.4 on 2021-03-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadb', '0004_conveyorhasvertex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'combination',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessorHasSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'processor_has_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SettingHasCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'setting_has_combination',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ProcessorHasOptions',
        ),
    ]
